pub mod config;
pub mod structs;
pub mod features;

use structs::OsceModel;

/// Load OSCE models (LACE, NoLACE, BBWENet) from weight data.
/// Matches C `osce_load_models` from osce.c.
///
/// NOTE: Full implementation requires the auto-generated model layer structs
/// (LACELayers, NOLACELayers, BBWENETLayers) from the weight data.
/// The model init functions are auto-generated by the Python weight-exchange
/// tools and will be ported when the build.rs codegen is implemented.
pub fn osce_load_models(
    _model: &mut OsceModel,
    _data: &[u8],
    _len: usize,
) -> i32 {
    // TODO: Parse weight blob and initialize LACE/NoLACE/BBWENet models.
    -1
}

/// Reset OSCE state for a given method.
/// Matches C `osce_reset` from osce.c.
pub fn osce_reset(model: &mut OsceModel, method: i32) {
    model.method = method;
}

/// Enhance a decoded SILK frame using OSCE.
/// Matches C `osce_enhance_frame` from osce.c.
///
/// NOTE: Full implementation requires:
/// 1. SILK decoder internal state (silk_decoder_state) for feature extraction
/// 2. Model layer structs loaded from weight data
/// 3. The adaptive layer processing chains (LACE/NoLACE/BBWENet)
///
/// The neural DSP primitives (AdaConv, AdaComb, AdaShape) are implemented
/// in the nndsp module and ready for use. Integration with SILK decoder
/// will be completed in Phase 7.
pub fn osce_enhance_frame(
    _model: &OsceModel,
    _xq: &mut [i16],
    _num_bits: i32,
) {
    // TODO: Implement OSCE enhancement pipeline.
    // 1. Extract features from SILK decoder state
    // 2. Run feature network (conv + GRU conditioning)
    // 3. Apply adaptive layers based on method:
    //    - LACE: 2 AdaComb + 1 AdaConv
    //    - NoLACE: 2 AdaComb + 4 AdaConv + 3 AdaShape
    // 4. De-emphasis and output
}
