// Model weight data module.
//
// In the C reference, model struct definitions (e.g., PitchDNN, FARGAN, PLCModel)
// and their init functions are auto-generated by the Python weight-exchange tools
// into *_data.h/c files. These are downloaded at build time (not checked in).
//
// In Rust, this module serves the same role. The build.rs will generate Rust source
// from the downloaded C data files, which will be included here via `include!`.
//
// Until the build.rs codegen is implemented, model structs are defined manually
// in their respective feature modules (pitchdnn.rs, fargan/, dred/, osce/, etc.)
// as those phases are implemented.

/// SHA256 hash of the current model weight tarball.
/// Used by build.rs to download from https://media.xiph.org/opus/models/
pub const MODEL_HASH: &str = "a5177ec6fb7d15058e99e57029746100121f68e4890b1467d4094aa336b6013e";

/// Base URL for model weight downloads.
pub const MODEL_URL: &str = "https://media.xiph.org/opus/models";
