use super::Activation;

/// Tanh lookup table from tansig_table.h (auto-generated by gen_tables).
/// Used by SIMD-optimized activation paths in future.
#[allow(dead_code)]
#[rustfmt::skip]
const TANSIG_TABLE: [f32; 201] = [
    0.000000, 0.039979, 0.079830, 0.119427, 0.158649,
    0.197375, 0.235496, 0.272905, 0.309507, 0.345214,
    0.379949, 0.413644, 0.446244, 0.477700, 0.507977,
    0.537050, 0.564900, 0.591519, 0.616909, 0.641077,
    0.664037, 0.685809, 0.706419, 0.725897, 0.744277,
    0.761594, 0.777888, 0.793199, 0.807569, 0.821040,
    0.833655, 0.845456, 0.856485, 0.866784, 0.876393,
    0.885352, 0.893698, 0.901468, 0.908698, 0.915420,
    0.921669, 0.927473, 0.932862, 0.937863, 0.942503,
    0.946806, 0.950795, 0.954492, 0.957917, 0.961090,
    0.964028, 0.966747, 0.969265, 0.971594, 0.973749,
    0.975743, 0.977587, 0.979293, 0.980869, 0.982327,
    0.983675, 0.984921, 0.986072, 0.987136, 0.988119,
    0.989027, 0.989867, 0.990642, 0.991359, 0.992020,
    0.992631, 0.993196, 0.993718, 0.994199, 0.994644,
    0.995055, 0.995434, 0.995784, 0.996108, 0.996407,
    0.996682, 0.996937, 0.997172, 0.997389, 0.997590,
    0.997775, 0.997946, 0.998104, 0.998249, 0.998384,
    0.998508, 0.998623, 0.998728, 0.998826, 0.998916,
    0.999000, 0.999076, 0.999147, 0.999213, 0.999273,
    0.999329, 0.999381, 0.999428, 0.999472, 0.999513,
    0.999550, 0.999585, 0.999617, 0.999646, 0.999673,
    0.999699, 0.999722, 0.999743, 0.999763, 0.999781,
    0.999798, 0.999813, 0.999828, 0.999841, 0.999853,
    0.999865, 0.999875, 0.999885, 0.999893, 0.999902,
    0.999909, 0.999916, 0.999923, 0.999929, 0.999934,
    0.999939, 0.999944, 0.999948, 0.999952, 0.999956,
    0.999959, 0.999962, 0.999965, 0.999968, 0.999970,
    0.999973, 0.999975, 0.999977, 0.999978, 0.999980,
    0.999982, 0.999983, 0.999984, 0.999986, 0.999987,
    0.999988, 0.999989, 0.999990, 0.999990, 0.999991,
    0.999992, 0.999992, 0.999993, 0.999994, 0.999994,
    0.999994, 0.999995, 0.999995, 0.999996, 0.999996,
    0.999996, 0.999997, 0.999997, 0.999997, 0.999997,
    0.999997, 0.999998, 0.999998, 0.999998, 0.999998,
    0.999998, 0.999998, 0.999999, 0.999999, 0.999999,
    0.999999, 0.999999, 0.999999, 0.999999, 0.999999,
    0.999999, 0.999999, 0.999999, 0.999999, 0.999999,
    1.000000, 1.000000, 1.000000, 1.000000, 1.000000,
    1.000000, 1.000000, 1.000000, 1.000000, 1.000000,
    1.000000,
];

/// Fast exp2 approximation matching C `lpcnet_exp2`.
fn lpcnet_exp2(x: f32) -> f32 {
    let integer = x.floor() as i32;
    if integer < -50 {
        return 0.0;
    }
    let frac = x - integer as f32;
    let f = 0.99992522 + frac * (0.69583354 + frac * (0.22606716 + 0.078024523 * frac));
    let bits = f.to_bits();
    let result = (bits.wrapping_add((integer as u32) << 23)) & 0x7fff_ffff;
    f32::from_bits(result)
}

fn lpcnet_exp(x: f32) -> f32 {
    lpcnet_exp2(x * 1.44269504)
}

/// Rational tanh approximation matching C `tanh_approx`.
fn tanh_approx(x: f32) -> f32 {
    const N0: f32 = 952.52801514;
    const N1: f32 = 96.39235687;
    const N2: f32 = 0.60863042;
    const D0: f32 = 952.72399902;
    const D1: f32 = 413.36801147;
    const D2: f32 = 11.88600922;
    let x2 = x * x;
    let num = (N2 * x2 + N1) * x2 + N0;
    let den = (D2 * x2 + D1) * x2 + D0;
    let result = num * x / den;
    result.clamp(-1.0, 1.0)
}

fn sigmoid_approx(x: f32) -> f32 {
    0.5 + 0.5 * tanh_approx(0.5 * x)
}

/// Apply activation function in-place.
/// Matches C `compute_activation_c` from nnet_arch.h.
///
/// SOFTMAX_HACK is always active (matching default C build):
/// Softmax just copies input without normalization, which is a no-op in-place.
pub fn compute_activation(data: &mut [f32], activation: Activation) {
    match activation {
        Activation::Linear | Activation::Softmax => {}
        Activation::Relu => {
            for x in data.iter_mut() {
                if *x < 0.0 {
                    *x = 0.0;
                }
            }
        }
        Activation::Sigmoid => {
            for x in data.iter_mut() {
                *x = sigmoid_approx(*x);
            }
        }
        Activation::Tanh => {
            for x in data.iter_mut() {
                *x = tanh_approx(*x);
            }
        }
        Activation::Swish => {
            for x in data.iter_mut() {
                let s = sigmoid_approx(*x);
                *x *= s;
            }
        }
        Activation::Exp => {
            for x in data.iter_mut() {
                *x = lpcnet_exp(*x);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tanh_approx_boundaries() {
        assert!((tanh_approx(0.0)).abs() < 1e-6);
        assert!((tanh_approx(4.0) - 1.0).abs() < 0.01);
        assert!((tanh_approx(-4.0) + 1.0).abs() < 0.01);
    }

    #[test]
    fn test_sigmoid_approx_boundaries() {
        assert!((sigmoid_approx(0.0) - 0.5).abs() < 1e-6);
        assert!(sigmoid_approx(10.0) > 0.99);
        assert!(sigmoid_approx(-10.0) < 0.01);
    }

    #[test]
    fn test_lpcnet_exp2_basic() {
        assert!((lpcnet_exp2(0.0) - 1.0).abs() < 0.001);
        assert!((lpcnet_exp2(1.0) - 2.0).abs() < 0.01);
        assert_eq!(lpcnet_exp2(-100.0), 0.0);
    }

    #[test]
    fn test_relu() {
        let mut data = [-2.0, -1.0, 0.0, 1.0, 2.0];
        compute_activation(&mut data, Activation::Relu);
        assert_eq!(data, [0.0, 0.0, 0.0, 1.0, 2.0]);
    }

    #[test]
    fn test_softmax_hack_is_noop() {
        let mut data = [1.0, 2.0, 3.0];
        let original = data;
        compute_activation(&mut data, Activation::Softmax);
        assert_eq!(data, original);
    }

    #[test]
    fn test_tansig_table_endpoints() {
        assert_eq!(TANSIG_TABLE[0], 0.0);
        assert_eq!(TANSIG_TABLE[200], 1.0);
    }
}
